import { resolveApiPath } from '$lib/utils/api-fetch';
import { getJsonHeaders } from '$lib/utils/api-headers';
import { serverStore } from '$lib/stores/server.svelte';
import { config } from '$lib/stores/settings.svelte';
import { ChatService } from './chat.service';
import { DatabaseService } from './database.service';
import { MessageRole } from '$lib/enums';
import type { DatabaseMessage } from '$lib/types/database';

/**
 * ContextCompactionService — proactive summary-buffer compaction.
 *
 * llama-server rejects any request whose prompt exceeds n_ctx (HTTP 400 with
 * n_prompt_tokens/n_ctx), which used to surface as a dead-end "start a new
 * conversation" dialog. This service prevents that: before a request is sent,
 * the assembled history is token-counted against the model's real context
 * window, and if it is too large the OLDEST turns are folded into a running
 * summary generated by the local model itself (the summary-buffer pattern —
 * same algorithm as LangChain's ConversationSummaryBufferMemory, ported
 * natively). Recent turns stay verbatim; the summary rides along as a system
 * message. Everything runs against the local server — no data leaves the box.
 *
 * The running summary is persisted on the conversation record (Dexie ignores
 * undeclared fields for indexing, so no schema migration), keyed to the last
 * message id it covers. Because conversations are trees (branch switching,
 * regenerate), the stored summary is only reused when that message id is
 * present in the branch being sent; otherwise it is discarded and rebuilt.
 *
 * Costs to be aware of: each compaction is one extra (non-streamed) model
 * call, and rewriting the front of the prompt invalidates llama-server's KV
 * prefix cache, forcing a full reprocess on the next turn. Both are why
 * compaction triggers rarely (threshold + hysteresis) rather than per-turn.
 */

// Compact when the estimated prompt exceeds this fraction of the usable
// context (n_ctx minus generation headroom). 0.85 leaves room for the model's
// reply plus estimation error without triggering constantly.
const TRIGGER_RATIO = 0.85;
// After compaction, keep verbatim tail messages up to this fraction of the
// usable context — the gap between the two ratios is the hysteresis that
// stops compaction from firing again on the very next turn.
const KEEP_RATIO = 0.5;
// Headroom reserved for the generated reply when max_tokens is unlimited.
const DEFAULT_RESERVE_TOKENS = 1024;
// Hard cap on the summary the model is asked to produce.
const SUMMARY_MAX_TOKENS = 400;
// Per-message chat-template overhead (role headers, separators) that
// /tokenize on raw text does not see.
const PER_MESSAGE_OVERHEAD_TOKENS = 6;

const SUMMARY_PREFIX = '[Conversation summary — earlier messages were compacted to fit the context window]\n';

// Progressive summarizer prompt (ported from LangChain's SUMMARY_PROMPT):
// folds new lines into the existing summary instead of re-summarizing from
// scratch, keeping each compaction call small and bounded.
function buildSummaryPrompt(existingSummary: string, newLines: string): string {
	return (
		'Progressively summarize the lines of conversation provided, adding onto the previous summary and returning a new summary. ' +
		'Keep concrete facts, names, dates, numbers, decisions, and open questions. Reply with the new summary only.\n\n' +
		`Current summary:\n${existingSummary || '(none)'}\n\n` +
		`New lines of conversation:\n${newLines}\n\nNew summary:`
	);
}

export interface CompactionResult {
	messages: DatabaseMessage[];
	compacted: boolean;
}

export interface ContextUsage {
	usedTokens: number;
	nCtx: number;
	usable: number;
	percent: number;
	/** True when a stored summary is shrinking the effective payload. */
	summarized: boolean;
}

export interface ManualCompactionResult {
	compacted: boolean;
	message: string;
}

export class ContextCompactionService {
	/** n_ctx and the send budget (n_ctx minus generation headroom), or null when unknown. */
	private static budget(): { nCtx: number; usable: number } | null {
		const nCtx = serverStore.contextSize;
		if (!nCtx || nCtx <= 0) return null;
		const maxTokens = Number(config().max_tokens);
		const reserve = maxTokens > 0 ? maxTokens : DEFAULT_RESERVE_TOKENS;
		const usable = nCtx - reserve;
		return usable > 0 ? { nCtx, usable } : null;
	}

	private static makeSummaryMessage(template: DatabaseMessage, summaryText: string): DatabaseMessage {
		return {
			...template,
			id: `compaction-${template.id}`,
			role: MessageRole.SYSTEM,
			content: SUMMARY_PREFIX + summaryText,
			reasoningContent: undefined,
			toolCalls: '',
			extra: undefined
		} as DatabaseMessage;
	}

	private static leadingSystemCount(messages: DatabaseMessage[]): number {
		let n = 0;
		while (n < messages.length && messages[n].role === MessageRole.SYSTEM) n++;
		return n;
	}

	/**
	 * If this conversation has a stored summary whose coverage boundary is on
	 * the given branch, returns the payload with the covered span replaced by
	 * the summary message — no model call involved. Otherwise returns the
	 * input array unchanged (same reference).
	 */
	private static async applyStoredSummary(
		convId: string,
		messages: DatabaseMessage[]
	): Promise<{ messages: DatabaseMessage[]; applied: boolean }> {
		const stored = (await DatabaseService.getConversation(convId))?.contextSummary;
		if (!stored?.text || !stored.upToMessageId) return { messages, applied: false };
		const boundary = messages.findIndex((m) => m.id === stored.upToMessageId);
		const firstChat = this.leadingSystemCount(messages);
		if (boundary < firstChat) return { messages, applied: false };
		const summaryMessage = this.makeSummaryMessage(messages[boundary], stored.text);
		return {
			messages: [...messages.slice(0, firstChat), summaryMessage, ...messages.slice(boundary + 1)],
			applied: true
		};
	}

	/**
	 * Token usage of the payload that WOULD be sent right now (stored summary
	 * applied when present), for the context indicator. Null when the server's
	 * context size is unknown.
	 */
	static async estimateUsage(convId: string, messages: DatabaseMessage[]): Promise<ContextUsage | null> {
		try {
			const budget = this.budget();
			if (!budget) return null;
			const effective = await this.applyStoredSummary(convId, messages);
			const counts = await this.countTokensPerMessage(effective.messages);
			if (!counts) return null;
			const usedTokens = counts.reduce((a, b) => a + b, 0);
			return {
				usedTokens,
				nCtx: budget.nCtx,
				usable: budget.usable,
				percent: Math.min(100, Math.round((usedTokens / budget.nCtx) * 100)),
				summarized: effective.applied
			};
		} catch {
			return null;
		}
	}

	/**
	 * User-initiated compaction (the indicator click): summarizes everything
	 * older than the keep-tail immediately, regardless of the automatic
	 * threshold. The stored summary then shrinks every subsequent send via
	 * applyStoredSummary. Returns a human-readable outcome either way.
	 */
	static async compactNow(convId: string, messages: DatabaseMessage[]): Promise<ManualCompactionResult> {
		try {
			const budget = this.budget();
			if (!budget) return { compacted: false, message: 'Context size unknown — is the server running?' };

			const counts = await this.countTokensPerMessage(messages);
			if (!counts) return { compacted: false, message: 'Could not measure the conversation.' };

			const firstChat = this.leadingSystemCount(messages);
			const keepBudget = budget.usable * KEEP_RATIO;
			let tailStart = messages.length;
			let tailTokens = 0;
			while (tailStart > firstChat) {
				const next = tailTokens + counts[tailStart - 1];
				if (next > keepBudget && messages.length - tailStart >= 2) break;
				tailTokens = next;
				tailStart--;
			}

			const pruned = messages.slice(firstChat, tailStart);
			if (pruned.length === 0) {
				return { compacted: false, message: 'Nothing to compact — the conversation still fits comfortably.' };
			}

			const stored = (await DatabaseService.getConversation(convId))?.contextSummary;
			let existingSummary = '';
			let toSummarize = pruned;
			if (stored?.text && stored.upToMessageId) {
				const boundary = pruned.findIndex((m) => m.id === stored.upToMessageId);
				if (boundary !== -1) {
					existingSummary = stored.text;
					toSummarize = pruned.slice(boundary + 1);
				}
			}
			if (toSummarize.length === 0 && existingSummary) {
				return { compacted: false, message: 'Already compacted — no new messages to fold in.' };
			}

			const summary = toSummarize.length ? await this.summarize(existingSummary, toSummarize) : existingSummary;
			if (!summary) return { compacted: false, message: 'The model did not produce a summary. Try again.' };

			await DatabaseService.updateConversation(convId, {
				contextSummary: { text: summary, upToMessageId: pruned[pruned.length - 1].id }
			});
			console.info(`[ContextCompaction] Manual compaction: ${pruned.length} message(s) folded into the running summary`);
			return { compacted: true, message: `Compacted ${pruned.length} older message${pruned.length === 1 ? '' : 's'} into a summary.` };
		} catch (error) {
			console.warn('[ContextCompaction] Manual compaction failed:', error);
			return { compacted: false, message: 'Compaction failed — see the console for details.' };
		}
	}
	/**
	 * Token-counts `messages` against the server's context window and, when
	 * over threshold, returns a rewritten list with the oldest turns replaced
	 * by a running summary. Returns the input untouched when compaction is
	 * disabled, not needed, or not possible (no n_ctx, tiny history, or any
	 * error — this must never block a send).
	 */
	static async maybeCompact(
		convId: string,
		messages: DatabaseMessage[]
	): Promise<CompactionResult> {
		const passthrough: CompactionResult = { messages, compacted: false };
		try {
			if (config().contextCompaction === false) return passthrough;

			const budgetInfo = this.budget();
			if (!budgetInfo) return passthrough;
			const { nCtx, usable } = budgetInfo;

			const counts = await this.countTokensPerMessage(messages);
			if (!counts) return passthrough;
			const total = counts.reduce((a, b) => a + b, 0);
			if (total <= usable * TRIGGER_RATIO) {
				// Under threshold, but a stored summary (e.g. from a manual
				// compaction) still shrinks the payload — apply it at zero cost.
				const effective = await this.applyStoredSummary(convId, messages);
				return { messages: effective.messages, compacted: effective.applied };
			}

			// Leading system messages are never summarized away.
			const firstChat = this.leadingSystemCount(messages);

			// Keep the newest tail within the keep budget. The last message pair
			// (current user turn + any tool results) is always kept regardless.
			const keepBudget = usable * KEEP_RATIO;
			let tailStart = messages.length;
			let tailTokens = 0;
			while (tailStart > firstChat) {
				const next = tailTokens + counts[tailStart - 1];
				if (next > keepBudget && messages.length - tailStart >= 2) break;
				tailTokens = next;
				tailStart--;
			}

			const pruned = messages.slice(firstChat, tailStart);
			if (pruned.length === 0) return passthrough;

			// Reuse the stored running summary when its coverage boundary is part
			// of the pruned span of THIS branch; otherwise rebuild from scratch.
			const conv = await DatabaseService.getConversation(convId);
			const stored = conv?.contextSummary;
			let existingSummary = '';
			let toSummarize = pruned;
			if (stored?.text && stored.upToMessageId) {
				const boundary = pruned.findIndex((m) => m.id === stored.upToMessageId);
				if (boundary !== -1) {
					existingSummary = stored.text;
					toSummarize = pruned.slice(boundary + 1);
				}
			}

			const summary = toSummarize.length
				? await this.summarize(existingSummary, toSummarize)
				: existingSummary;
			if (!summary) return passthrough;

			await DatabaseService.updateConversation(convId, {
				contextSummary: { text: summary, upToMessageId: pruned[pruned.length - 1].id }
			});

			// Synthetic system message carrying the summary. It is API-payload
			// only — never written to the message tree — so the visible
			// conversation history stays complete.
			const summaryMessage = this.makeSummaryMessage(pruned[pruned.length - 1], summary);

			console.info(
				`[ContextCompaction] Compacted ${pruned.length} message(s) (~${total} tokens > ${Math.round(usable * TRIGGER_RATIO)} threshold, n_ctx ${nCtx})`
			);
			return {
				messages: [...messages.slice(0, firstChat), summaryMessage, ...messages.slice(tailStart)],
				compacted: true
			};
		} catch (error) {
			console.warn('[ContextCompaction] Skipping compaction due to error:', error);
			return passthrough;
		}
	}

	/**
	 * Exact-ish token counts per message: one /tokenize call on the
	 * concatenated text (real tokenizer, no prompt processing) apportioned per
	 * message, plus fixed per-message template overhead. Falls back to a
	 * chars/3 estimate if /tokenize is unavailable (conservative — favors
	 * compacting slightly early over a hard 400).
	 */
	private static async countTokensPerMessage(messages: DatabaseMessage[]): Promise<number[] | null> {
		const texts = messages.map((m) => this.messageText(m));

		try {
			const res = await fetch(resolveApiPath('./tokenize'), {
				method: 'POST',
				headers: getJsonHeaders(),
				body: JSON.stringify({ content: texts.join('\n') })
			});
			if (res.ok) {
				const data = await res.json();
				const totalTokens: number | undefined = Array.isArray(data?.tokens)
					? data.tokens.length
					: undefined;
				if (totalTokens !== undefined) {
					const totalChars = Math.max(1, texts.reduce((a, t) => a + t.length, 0));
					return texts.map(
						(t) => Math.ceil((t.length / totalChars) * totalTokens) + PER_MESSAGE_OVERHEAD_TOKENS
					);
				}
			}
		} catch {
			/* fall through to estimate */
		}
		return texts.map((t) => Math.ceil(t.length / 3) + PER_MESSAGE_OVERHEAD_TOKENS);
	}

	private static messageText(message: DatabaseMessage): string {
		let text = typeof message.content === 'string' ? message.content : '';
		if (message.reasoningContent) text += '\n' + message.reasoningContent;
		if (message.toolCalls) text += '\n' + message.toolCalls;
		if (message.extra?.length) {
			for (const extra of message.extra) {
				if ('content' in extra && typeof extra.content === 'string') text += '\n' + extra.content;
			}
		}
		return `${message.role}: ${text}`;
	}

	/** One non-streamed call to the local model with the progressive prompt. */
	private static async summarize(
		existingSummary: string,
		messages: DatabaseMessage[]
	): Promise<string | null> {
		const newLines = messages
			.map((m) => this.messageText(m))
			.join('\n')
			// The summarizer input itself must fit comfortably — clip defensively.
			.slice(0, 24000);

		const result = await ChatService.sendMessage(
			[{ role: MessageRole.USER, content: buildSummaryPrompt(existingSummary, newLines) }],
			{
				stream: false,
				temperature: 0.2,
				max_tokens: SUMMARY_MAX_TOKENS,
				enableThinking: false
			}
		);
		const text = typeof result === 'string' ? result.trim() : '';
		return text || null;
	}
}
